services:
  crafting-app:
    build: .
    container_name: crafting-nextjs
    restart: unless-stopped
    env_file: .env
    expose:
      - "3000"
    volumes:
      - ./data:/app/data
      - ./public/uploads:/app/public/uploads
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true