services:
  crafting-app:
    build: .
    container_name: crafting-nextjs
    restart: unless-stopped
    user: "1000:1000" # Force the container to run as a standard user
    env_file: .env
    expose:
      - "3000"
    volumes:
      - ./sqlite.db:/app/sqlite.db
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true